### ISSUE TITLE
Very strange request!

### ISSUE THREAD

**Issue by richardatsley** [sekwah41/Re-Skin#123]
Hello! I am a big fan of this mod, I downloaded it yesterday to help aid with a project I've been working on for quite some time, but! I'd like to use some other mods alongside it, do you think it's possible to make a _downgraded_ version to 1.19.3? If not, that's fine too, but I can't seem to find any mods for that version that allows for fast HD Skin processing like this one, thank you for your time :)!

**Comment by sekwah41** [comment]
2.6.1 should work with 1.19.3 https://modrinth.com/mod/reskin/version/2.6.1

its 1.19.4 that I forgot to add support for in sekclib though you can force it to work, i didnt publish a version for it

**Comment by sekwah41** [comment]
Closed as I believe that the version is already supported.

**Comment by richardatsley** [comment]
I forgot to say!! This does work and my project is moving swimmingly! Thank you :)!!
