### ISSUE TITLE
I don't see other player skin

### ISSUE THREAD

**Issue by Mattygamer** [sekwah41/Re-Skin#13]
Hi, i installed the mod on aternos server and is correctly working, the only issue that i noticed is that i see my skin but not the other player skin. The same things appen to other player they only see their skin.

**Comment by sekwah41** [comment]
Which version are you using?

Are you in online or offline mode?

Does this happen when the players initially set their skins or after it's been loaded in?

**Comment by Mattygamer** [comment]
I'm using the 1.2.0, the server is in offline mode but i have minecraft premium, this happen anyway

**Comment by sekwah41** [comment]
"Does this happen when the players initially set their skins or after it's been loaded in?"

This was the most important question

**Comment by Mattygamer** [comment]
when the players initially set their skins

**Comment by sekwah41** [comment]
Which version of mc are you using?

**Comment by Mattygamer** [comment]
1.12.2

**Comment by sekwah41** [comment]
We no longer support 1.12.2. Sorry.

You need to make sure that you are using.

**Comment by Mattygamer** [comment]
what i need to use?

**Comment by sekwah41** [comment]
Sorry was going to say using 1.2. but saw that and forgot to remove the message. If it's not working I am not too sure whats going on as I haven't touched 1.12 code in over a year.

**Comment by Mattygamer** [comment]
maybe the offline mode?

**Comment by sekwah41** [comment]
I doubt it. Either way, we don't support 1.12.2 anymore.

**Comment by Mattygamer** [comment]
ok thanks
