### ISSUE TITLE
Multiplayer skins not working.

### ISSUE THREAD

**Issue by Gamer101233** [sekwah41/Re-Skin#130]
When i play on a LAN or multiplayer game with someone i have a issue where i use the command to set my skin and it works for me but, when the other player does it for them selfs or if i do it for them it changes again my skin im not sure whats causing this but, me and my friend wanted to use our own custom skins for our modpack and it only seems to update the skin for the person who is hosting the world.

Constantly updates the hosts skin no matter what command you use
wheather its from the hosts side or the players side who wants to change their
skin on minecraft using this mod.

**Comment by sekwah41** [comment]
What launcher are you using?

**Comment by Gamer101233** [comment]
im using the curseforge with minecraft 1.12.2 and it loads the minecraft launcher when i press play.

**Comment by sekwah41** [comment]
I don't support updates for the older versions but there isn't any reason why it should have stopped working 🤔

**Comment by sekwah41** [comment]
Not sure if its related to #133  at all due to imgur changes and issues.

**Comment by Gamer101233** [comment]
odd thing is that in that issue #133 i dont have that happening and i created a multiplayer server and tried it on there on another player and it worked for them it changed their skin on the server but, when i use singleplayer and open to lan and have the user join and try to change their skin it does not change their skin it only changes my skin.

**Comment by sekwah41** [comment]
Are you using offline mode or online? Offline can do some odd stuff with uuid. Though shouldn't.

**Comment by Gamer101233** [comment]
Im using online mode in my server but, for the LAN games i have on my local network thats where the issue is with the mod not letting players change their skin but, it only allows the host to have their skin changed.
just the odd thing is how the server lets all users including me change their skin but, when it comes to LAN hosted worlds it only allows the host to change their skin no matter the username you input in the command.

**Comment by sekwah41** [comment]
I'll have to look into that. There's a good chance lan handles game profiles slightly different or I've messed up somewhere detecting client vs server.

**Comment by Gamer101233** [comment]
Ah i see. just hopeing that this issue can be fixed for LAN conections for 1.12.2 forge so i can continue my modpack with people on my LAN.

**Comment by sekwah41** [comment]
It shouldnt be too difficult to setup the forge server on your local though I can understand that you want to do the lan for ease likey :P I am unsure why the lan doesn't work though.

**Comment by sekwah41** [comment]
For now the fix is to set the whitelist to https://reskinproxy.sekwah.com/

You can use this page to create the url's easier

https://www.sekwah.com/reskin/

Will close this as its going to take more time to port to older versions than its worth to fix. This "temp fix" will become a more perma fix for pre 1.20

**Comment by sekwah41** [comment]
Will re-open these should they not work though I dont maintain 1.12 and 1.12 at least has very different code to the newer versions.
