### ISSUE TITLE
No way to reset skin

### ISSUE THREAD

**Issue by lubcubsgaming** [sekwah41/Re-Skin#131]
Hey there! I am using version 2.6.1 for 1.19.2. There is no way to reset the skin back to the default player skin. The curse forge page says to do </setskin reset> but that is not working. It does not appear to be added at all.

Not sure if its been added to newer versions but I did see that with the release of the version 3.0.0 you stated you dropped support for 1.19 but on the curse page it also says you plan on adding the reset feature to version 1.16 of minecraft, so wanted to bring this up as a bug.

Great mod! Used it for 90% of projects when I worked for LogDotZip and Craftee. Not using it much anymore with BeckBroJack but I solely work in 1.19 right now and needed a mod to change skins again so wanted to use this mod but with the skin reset feature not working, I am unable to use this.

**Comment by sekwah41** [comment]
It has switched to a dedicated /clearskin command :)

**Comment by lubcubsgaming** [comment]
Oh. Lol, I tried so many different ways and ended up being stuck as an Alex skin xD Didn't see the clearskin command xD My bad! Thanks!
