### ISSUE TITLE
Skin change issue

### ISSUE THREAD

**Issue by Gamer101233** [sekwah41/Re-Skin#136]
When changing skins now they change you to a steve and i cant fix this issue at all iv tried many different imgur images i had for the skin mod and new when i go to copy the .png link and use the setskin command me and whoever else is on the world with me only sees me as a steve not my new skin and sometimes it will show on my side my skin that i changed into and on other users side only a steve.

**Comment by Gamer101233** [comment]
Issue is very similer to iddue #133  
i followed the steps for the one link to your server and added the .png side of the link to it
and now its changing on my side and users can see new skins i set.

Is there any sort of way i can fix this so i can use the default links provided by them?

**Comment by sekwah41** [comment]
Not currently. What version of the game are you using?

**Comment by Gamer101233** [comment]
using version 1.12.2

**Comment by Gamer101233** [comment]
Issue still is active and im not sure on how to fix this.

**Comment by sekwah41** [comment]
Not sure atm how to fix it in 1.12.2 but I've not had a chance to do hotfixes for the others yet.

**Comment by Gamer101233** [comment]
Alright

**Comment by sekwah41** [comment]
For now the fix is to set the whitelist to https://reskinproxy.sekwah.com/

You can use this page to create the url's easier

https://www.sekwah.com/reskin/

Will close this as its going to take more time to port to older versions than its worth to fix. This "temp fix" will become a more perma fix for pre 1.20
