### ISSUE TITLE
Whitelisting Sites

### ISSUE THREAD

**Issue by Stormrunner1981** [sekwah41/Re-Skin#14]
I've tried /setskin and /whitelist in game with no results. I'm hosting on my own site, and it just denies my skins because I cannot whitelist them.

Outside I edited the config file, but the mod reset it.  I was not able to do whitelisting through the mod section in forge.

**Comment by sekwah41** [comment]
There may be a glitch atm where its resetting the list constantly. Ill have to take a look this weekend.

**Comment by Stormrunner1981** [comment]
> 
> 
> There may be a glitch atm where its resetting the list constantly. Ill have to take a look this weekend.

Thank you for looking into it.

**Comment by sekwah41** [comment]
The issue has been fixed and will be released in the next few days (likely tomorrow)

**Comment by Stormrunner1981** [comment]
Thank you, much appreciated :).
