### ISSUE TITLE
feat: pleeeeeeeeeeeaaaase  update 1.21 for fabric offline server

### ISSUE THREAD

**Issue by GodReza** [sekwah41/Re-Skin#145]
**Is Your Feature Request Related to a Problem? Please Describe.**
A clear and concise description of what the problem is. For example, "I'm always frustrated when I have to manually sort items into chests."

**Minecraft and Mod Information**
- Minecraft Version: [e.g., 1.16.5]
- Mod Version (if applicable): [e.g., 2.1.0]
- Forge/Fabric Version : [Specify Forge or Fabric and version]
- Are you using other mods? [yes/no]
  - Mention any mods that you may want to explore compatibility with or integration with.

**Describe the Solution You'd Like**
A clear and concise description of what you want to happen. Include any specific mechanics or changes you envisage, such as new items, game mechanics, or user interface changes.

**Describe Alternatives You've Considered**
A clear and concise description of any alternative solutions or features you've considered. This could include how other mods achieve similar results or different ways to solve the same problem.

**Additional Context**
Add any other context, screenshots, or sketches about the feature request here. This could include examples from other games or mods that illustrate what you're looking for, or more detailed descriptions of how this feature would fit into the mod.

**Comment by sekwah41** [comment]
I dont currently support fabric, maybe once ive got sekclib supported on fabric, but given my limited time and how few people use fabric in comparison its not worth focusing on.

**Comment by sekwah41** [comment]
Also please fill out issue requests properly please or add a body to add some context.
