### ISSUE TITLE
Url whitelist blocking /setskin reset command

### ISSUE THREAD

**Issue by Kariaro** [sekwah41/Re-Skin#32]
https://github.com/sekwah41/Re-Skin/blob/770c2c04d8af2fad4125a82d711bc85b9c1d2ae0/src/main/java/com/sekwah/reskin/client/ClientSkinManager.java#L49

If this was an intended functionallity I would class this as a bug introduced by the url checking algorithm.

This error is generated not from the execute method but from the URLArgument type class.

**Comment by sekwah41** [comment]
See the following code

https://github.com/sekwah41/Re-Skin/blob/770c2c04d8af2fad4125a82d711bc85b9c1d2ae0/src/main/java/com/sekwah/reskin/commands/ClearSkinCommand.java#L48

That is why this exists.

**Comment by sekwah41** [comment]
It's for internally tracking when it should be set back as it's not possible as a normal set string.

**Comment by Kariaro** [comment]
https://github.com/sekwah41/Re-Skin/blob/770c2c04d8af2fad4125a82d711bc85b9c1d2ae0/src/main/java/com/sekwah/reskin/commands/SetSkinCommand.java#L53

Why is the setskin command skipping the whitelist check if the input url is `reset` then?

**Comment by sekwah41** [comment]
Because an old feature that was an alternative that I just hadn't fully removed. I should remove that code.
