### ISSUE TITLE
Skins dont load after rejoining a server.

### ISSUE THREAD

**Issue by TheTrustBucket** [sekwah41/Re-Skin#90]
Forge 1.16.5. I set my skin on the server but when i disconnect, my skin is reset to vanilla.

**Comment by sekwah41** [comment]
I need to check why this is the case, for some reason this wasn't flagged as an issue for a long time and suddenly its become a problem or people have only just started reporting it. Seeing as external network info is involved it could be external.

**Comment by sekwah41** [comment]
illl also have to take a look at porting fixes back to 1.16.5 as we only tend to support the latest

**Comment by sekwah41** [comment]
Should hopefully be fixed as part of the 1.19 updates.

**Comment by sekwah41** [comment]
Closing for now
